version: '3.7'
services:
  traefik:
    image: traefik:v2.2
    networks:
      - oauth
    command: >
      --providers.docker
      --entrypoints.web.address=:80
      --entrypoints.web.http.redirections.entryPoint.to=websecure
      --entrypoints.web.http.redirections.entryPoint.scheme=https
      --entrypoints.websecure.address=:443
      --certificatesresolvers.lestaging.acme.email=<EMAIL@EXAMPLE.COM>
      --certificatesresolvers.lestaging.acme.storage=/etc/traefik/acme/acme.json
      --certificatesresolvers.lestaging.acme.httpchallenge.entrypoint=web
      #--certificatesresolvers.lestaging.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    ports:
    - "80:80"
    - "443:443"
    volumes:
      - acme:/etc/traefik/acme
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  oauthproxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v6.0.0
    command: --upstream=http://phpmyadmin:80
    labels:
      - traefik.http.routers.oauthproxy.rule=Host(`vhost.example.com`)
      - traefik.http.routers.oauthproxy.tls=true
      - traefik.http.routers.oauthproxy.tls.certresolver=lestaging
      - traefik.http.services.oauthproxy.loadbalancer.server.port=4180
    environment:
     - OAUTH2_PROXY_PROVIDER=gitlab
     - OAUTH2_PROXY_CLIENT_ID=<PUT_CLIENT_ID_HERE>
     - OAUTH2_PROXY_CLIENT_SECRET=<PUT_CLIENT_SECRET_HERE>
     - OAUTH2_PROXY_GITLAB_GROUPS=gitlab-group-1,gitlab-group-2
     - OAUTH2_PROXY_COOKIE_SECRET=whateverrandomstring
     - OAUTH2_PROXY_EMAIL_DOMAINS=*
     - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
     - OAUTH2_PROXY_STANDARD_LOGGING=true
     - OAUTH2_PROXY_AUTH_LOGGING=true
     - OAUTH2_PROXY_REQUEST_LOGGING=true
    networks:
      - oauth
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOSTS=host-a.example.com,host-b.example.com
    networks:
      - oauth
    restart: always

volumes:
  acme: {}

networks:
  oauth: {}
